language: ruby
rvm:
  - 2.3.1
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database recordly_test' -U postgres
bundler_args: --binstubs=./bundler_stubs
